# Generated by Django 4.2.4 on 2023-08-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.IntegerField(default=0)),
                ('field3', models.TextField(max_length=500)),
                ('field4', models.CharField(max_length=200)),
                ('field5', models.IntegerField(default=0)),
                ('field6', models.TextField(max_length=500)),
                ('field7', models.CharField(max_length=200)),
                ('field8', models.IntegerField(default=0)),
                ('field9', models.TextField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
